-- CREATING TABLE: CATEGORIES
CREATE TABLE  CATEGORIES  (
   CATEGORY_CODE int NOT NULL,
   CATEGORY_NAME  VARCHAR(25) NOT NULL,
   DESCRIPTION    VARCHAR(100) NOT NULL,
   CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_CODE)
   );


  -- CREATING TABLE: CUSTOMERS
  CREATE TABLE CUSTOMERS   (
   CUSTOMER_CODE CHAR(5) NOT NULL,
   COMPANY NVARCHAR(40) NOT NULL,
   ADDRESS NVARCHAR(60) NOT NULL,
   CITY VARCHAR(30) NOT NULL,
   POSTAL_CODE VARCHAR(10) NOT NULL,
   COUNTRY VARCHAR(15) NOT NULL,
   PHONE VARCHAR(24) NOT NULL,
   FAX VARCHAR(24),
   CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_CODE)
  );


  -- CREATING TABLE: ORDERS
  CREATE TABLE ORDERS  (
   ORDER_NUMBER INT NOT NULL,
   CUSTOMER_CODE   CHAR(5) NOT NULL,
   EMPLOYEE_ID INT NOT NULL,
   ORDER_DATE DATE NOT NULL,
   SHIP_DATE DATE,
   SHIPPING_COST DECIMAL (10,2),
   CONSTRAINT PK_ORDERS  PRIMARY KEY (ORDER_NUMBER)
    );
    
    -- CREATING TABLE: ORDERS_DETAILS
    CREATE TABLE ORDER_DETAILS  (
   ORDER_NUMBER INT NOT NULL,
   PRODUCT_REF INT NOT NULL,
   UNIT_PRICE INT NOT NULL,
   QUANTITY INT NOT NULL,
   DISCOUNT FLOAT NOT NULL,
   CONSTRAINT PK_DETAILS_ORDERS  PRIMARY KEY (ORDER_NUMBER , PRODUCT_REF )
  );


  -- CREATING TABLE: EMPLOYEES
  CREATE TABLE EMPLOYEES (
   EMPLOYEE_ID INT NOT NULL,
   REPORTS_TO INT,
   LAST_NAME NVARCHAR(40) NOT NULL,
   FIRST_NAME NVARCHAR(30) NOT NULL,
   POSITION VARCHAR(30) NOT NULL,
   TITLE VARCHAR(5) NOT NULL,
   BIRTH_DATE DATE NOT NULL,
   HIRE_DATE DATE NOT NULL,
   SALARY INT NOT NULL,
   COMMISSION INT,
   CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
  );


  -- CREATING TABLE: SUPPLIERS
  CREATE TABLE SUPPLIERS  (
   SUPPLIER_ID INT NOT NULL,
   COMPANY NVARCHAR(40) NOT NULL,
   ADDRESS NVARCHAR(60) NOT NULL,
   CITY VARCHAR(30) NOT NULL,
   POSTAL_CODE VARCHAR(10) NOT NULL,
   COUNTRY VARCHAR(15) NOT NULL,
   PHONE VARCHAR(24) NOT NULL,
   FAX VARCHAR(24),
   CONSTRAINT PK_SUPPLIERS PRIMARY KEY (SUPPLIER_ID)
  );


  -- CREATING TABLE: PRODUCTS
CREATE TABLE PRODUCTS (
   PRODUCT_REF INT NOT NULL,
   PRODUCT_NAME NVARCHAR(40) NOT NULL,
   SUPPLIER_ID INT NOT NULL,
   CATEGORY_CODE INT NOT NULL,
   QUANTITY VARCHAR(30),
   UNIT_PRICE INT NOT NULL,
   UNITS_IN_STOCK INT,
   UNITS_ON_ORDER INT,
   UNAVAILABLE INT,
   CONSTRAINT PK_Project_PRODUCTS  PRIMARY KEY (PRODUCT_REF)
  );

  -- THE FOREIGN KEYS

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CUSTOMERS 
FOREIGN KEY (CUSTOMER_CODE) REFERENCES CUSTOMERS (CUSTOMER_CODE);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_EMPLOYEES  
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_ORDERS 
FOREIGN KEY (ORDER_NUMBER) REFERENCES ORDERS  (ORDER_NUMBER);

ALTER TABLE ORDER_DETAILS ADD CONSTRAINT FK_ORDER_DETAILS_PRODUCTS   
FOREIGN KEY (PRODUCT_REF) REFERENCES PRODUCTS  (PRODUCT_REF);

ALTER TABLE EMPLOYEES  ADD CONSTRAINT FK_EMPLOYEES_EMPLOYES 
FOREIGN KEY (REPORTS_TO) REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORIE 
FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES (CATEGORY_CODE);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_SUPPLIERS  
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIER_ID);
