-- 1. WHICH PRODUCTS DRIVE THE MOST SALES?
SELECT 
    P.PRODUCT_REF,
    P.PRODUCT_NAME,
    SUM(OD.QUANTITY) AS Total_Quantity_Sold
FROM ORDER_DETAILS OD
JOIN PRODUCTS P 
    ON OD.PRODUCT_REF = P.PRODUCT_REF
GROUP BY 
    P.PRODUCT_REF, 
    P.PRODUCT_NAME
ORDER BY 
    Total_Quantity_Sold DESC;




-- 2. WHO ARE OUR TOP 5 HIGHEST-VALUE CUSTOMERS, AND WHAT PERCENTAGE OF TOTAL REVENUE DO THEY CONTRIBUTE?
SELECT 
    C.CUSTOMER_CODE,
    C.COMPANY,
    SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) AS Customer_Spend,
    ROUND(
        SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) * 100.0 
        / (SELECT SUM(QUANTITY * UNIT_PRICE * (1 - DISCOUNT)) FROM ORDER_DETAILS), 
        2
    ) AS Percent_Of_Total_Revenue
FROM CUSTOMERS C
JOIN ORDERS O 
    ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD 
    ON O.ORDER_NUMBER = OD.ORDER_NUMBER
GROUP BY 
    C.CUSTOMER_CODE, 
    C.COMPANY
ORDER BY 
    Customer_Spend DESC;   

-- 3. HOW IS SALES PERFORMANCE DISTRIBUTED ACROSS EMPLOYEES?
SELECT 
    E.FIRST_NAME, 
    E.LAST_NAME,
    SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) AS Total_Sales,
    ROUND(
        SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) * 100.0 
        / (SELECT SUM(QUANTITY * UNIT_PRICE * (1 - DISCOUNT)) FROM ORDER_DETAILS), 
        2
    ) AS Pct_Of_Total_Revenue
FROM EMPLOYEES E
JOIN ORDERS O ON E.EMPLOYEE_ID = O.EMPLOYEE_ID
JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
GROUP BY E.FIRST_NAME, E.LAST_NAME
ORDER BY Total_Sales DESC;

-- 4. SUPPLIERS OF BEVERAGES
SELECT DISTINCT 
    s.SUPPLIER_ID,
    s.COMPANY,
    s.ADDRESS,
    s.PHONE
FROM SUPPLIERS s
JOIN PRODUCTS p 
    ON s.SUPPLIER_ID = p.SUPPLIER_ID
JOIN CATEGORIES c 
    ON p.CATEGORY_CODE = c.CATEGORY_CODE
WHERE UPPER(c.CATEGORY_NAME) = 'Beverages';


-- 5. CUSTOMER WHO HAS ORDERED ALL PRODUCTS
SELECT c.CUSTOMER_CODE, c.COMPANY, c.PHONE
FROM CUSTOMERS c
WHERE c.CUSTOMER_CODE IN (
    SELECT o.CUSTOMER_CODE
    FROM ORDERS o
    JOIN ORDER_DETAILS od ON o.ORDER_NUMBER = od.ORDER_NUMBER
    GROUP BY o.CUSTOMER_CODE
    HAVING COUNT(DISTINCT od.PRODUCT_REF) = (SELECT COUNT(*) FROM PRODUCTS)
);

-- 6. RANK PRODUCTS BY SALES WITHIN EACH CATEGORY — NOT JUST OVERALL
SELECT 
    C.CATEGORY_NAME,
    P.PRODUCT_NAME,
    SUM(OD.QUANTITY) AS Units_Sold,
    RANK() OVER (PARTITION BY C.CATEGORY_NAME 
    ORDER BY SUM(OD.QUANTITY) DESC) AS Rank_In_Category
FROM ORDER_DETAILS OD
JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
JOIN CATEGORIES C ON P.CATEGORY_CODE = C.CATEGORY_CODE
GROUP BY C.CATEGORY_NAME, P.PRODUCT_NAME
ORDER BY C.CATEGORY_NAME, Rank_In_Category;
​

-- 7. RUNNING TOTAL OF MONTHLY REVENUE — TRACK CUMULATIVE GROWTH
SELECT
    FORMAT(O.ORDER_DATE, 'MMM yyyy') AS [Month],
    SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) AS Monthly_Revenue,
    SUM(
        SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT))
    ) OVER
    (
        ORDER BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)
    ) AS Running_Total_Revenue
FROM ORDERS O
JOIN ORDER_DETAILS OD
    ON O.ORDER_NUMBER = OD.ORDER_NUMBER
GROUP BY
    YEAR(O.ORDER_DATE),
    MONTH(O.ORDER_DATE),
    FORMAT(O.ORDER_DATE, 'MMM yyyy')
ORDER BY
    YEAR(O.ORDER_DATE),
    MONTH(O.ORDER_DATE);

-- 8.EACH CUSTOMER'S SINGLE FAVOURITE PRODUCT
SELECT Company, Product_Name, Units_Ordered
FROM (
    SELECT 
        C.COMPANY,
        P.PRODUCT_NAME,
        SUM(OD.QUANTITY) AS Units_Ordered,
        ROW_NUMBER() OVER (PARTITION BY C.COMPANY 
        ORDER BY SUM(OD.QUANTITY) DESC) AS rating_number
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
    JOIN ORDER_DETAILS OD ON O.ORDER_NUMBER = OD.ORDER_NUMBER
    JOIN PRODUCTS P ON OD.PRODUCT_REF = P.PRODUCT_REF
    GROUP BY C.COMPANY, P.PRODUCT_NAME
) ranked
WHERE rating_number = 1
ORDER BY Product_Name, Units_Ordered DESC;
​

-- 9. WHICH COUNTRIES GENERATE THE HIGHEST REVENUE
SELECT
    C.COUNTRY,
    SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT)) AS Total_Revenue,
    ROUND(
        SUM(OD.QUANTITY * OD.UNIT_PRICE * (1 - OD.DISCOUNT))
        *100.0/
        (
            SELECT SUM(QUANTITY*UNIT_PRICE*(1-DISCOUNT))
            FROM ORDER_DETAILS
        ),
        2
    ) AS Percent_Of_Total_Revenue
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_CODE = O.CUSTOMER_CODE
JOIN ORDER_DETAILS OD
    ON O.ORDER_NUMBER = OD.ORDER_NUMBER
GROUP BY
    C.COUNTRY
ORDER BY
    Total_Revenue DESC;